spring:
  application:
    name: transaction
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        show_sql: true
#        format_sql: true
  h2:
    console:
      enabled: true
      # default path: h2-console
      path: /h2-ui

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}
  paths-to-exclude: /error
  swagger-ui:
    path: /swagger-ui

api:
  exchange-rate:
    base-url: https://api.fiscaldata.treasury.gov/services/api/fiscal_service